### ISSUE TITLE
Outdated Gradle

### ISSUE THREAD

**Issue by josephworks** [Timardo/ContentCreator#1]
I saw
`distributionUrl=https\://services.gradle.org/distributions/gradle-2.14-bin.zip`
In Gradle/wrapper/
And Gradle 5.x has been released so I recommend you upgrade to that.

**Comment by Timardo** [comment]
Although I don't think outdated build system which works and even is packed with Forge MDK is an issue, I updated Gradle to the highest version possible. Since ForgeGradle plugin uses deprecated Gradle API which is not available in Gradle 5+ I am not able to go beyond version 4.10.2

**Comment by josephworks** [comment]
Oh ok

Joseph R.
